apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdf-chatbot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shahadthet-gif/cdf-chatbot-poc.git
    targetRevision: main
    path: kubernetes
    directory:
      recurse: true
      exclude: "argocd/*"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
