apiVersion: v1
kind: Service
metadata:
  name: chatwoot-service
  labels:
    app: chatwoot-proxy
spec:
  selector:
    app: chatwoot-proxy
  ports:
      - port: 5600
        targetPort: 5600
  type: ClusterIP
