server {
    listen 5500;

    root /usr/share/nginx/html;
    index index.html;

  location / {
    root /usr/share/nginx/html;
    index index.html;
}
    location /rasa/ {
        proxy_pass http://rasa-service:7860/;
    }

    location /api/handoff/ {
        proxy_pass http://chatwoot-service:5600;
    }
}